### ISSUE TITLE
TA Feedback (milestone 2): model_fitting.py

### ISSUE THREAD

**Issue by jbourak** [UBC-MDS/DSCI_522_group27#79]
I get the following errors when I run `python src/model_fitting.py data results`
```
TypeError: Cannot read property 'getContext' of null
    at resize (/Users/jbourak/opt/miniconda3/lib/vega-cli/node_modules/vega-scenegraph/build/vega-scenegraph.js:3377:26)
    at CanvasRenderer.prototype$6.resize (/Users/jbourak/opt/miniconda3/lib/vega-cli/node_modules/vega-scenegraph/build/vega-scenegraph.js:3427:5)
    at CanvasRenderer.prototype$4.initialize (/Users/jbourak/opt/miniconda3/lib/vega-cli/node_modules/vega-scenegraph/build/vega-scenegraph.js:2989:17)
    at CanvasRenderer.prototype$6.initialize (/Users/jbourak/opt/miniconda3/lib/vega-cli/node_modules/vega-scenegraph/build/vega-scenegraph.js:3422:28)
    at initializeRenderer (/Users/jbourak/opt/miniconda3/lib/vega-cli/node_modules/vega-view/build/vega-view.js:630:8)
    at renderHeadless (/Users/jbourak/opt/miniconda3/lib/vega-cli/node_modules/vega-view/build/vega-view.js:736:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'getContext' of null
    at resize (/Users/jbourak/opt/miniconda3/lib/vega-cli/node_modules/vega-scenegraph/build/vega-scenegraph.js:3377:26)
    at CanvasRenderer.prototype$6.resize (/Users/jbourak/opt/miniconda3/lib/vega-cli/node_modules/vega-scenegraph/build/vega-scenegraph.js:3427:5)
    at CanvasRenderer.prototype$4.initialize (/Users/jbourak/opt/miniconda3/lib/vega-cli/node_modules/vega-scenegraph/build/vega-scenegraph.js:2989:17)
    at CanvasRenderer.prototype$6.initialize (/Users/jbourak/opt/miniconda3/lib/vega-cli/node_modules/vega-scenegraph/build/vega-scenegraph.js:3422:28)
    at initializeRenderer (/Users/jbourak/opt/miniconda3/lib/vega-cli/node_modules/vega-view/build/vega-view.js:630:8)
    at renderHeadless (/Users/jbourak/opt/miniconda3/lib/vega-cli/node_modules/vega-view/build/vega-view.js:736:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
resulting in empty PNG files for the outputs.

**Comment by nashmakh** [comment]
This issue can be fixed by running `npm install -g vega vega-lite vega-cli canvas` in the base environment
